# Generated by Django 4.2.1 on 2023-06-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="basket_history",
            field=models.JSONField(default=dict),
        ),
    ]
