# Generated by Django 4.2.1 on 2023-06-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_alter_basket_managers"),
        ("orders", "0005_alter_order_basket_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="purchased_goods",
            field=models.ManyToManyField(to="products.product"),
        ),
    ]
