# Generated by Django 4.2.1 on 2023-06-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_purchased_goods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='basket_history',
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
