# Generated by Django 4.2.1 on 2023-06-02 10:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productcategory",
            options={"verbose_name": "category", "verbose_name_plural": "categories"},
        ),
    ]
