# Generated by Django 4.2.1 on 2023-06-16 14:31

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_basket"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="basket",
            managers=[
                ("object", django.db.models.manager.Manager()),
            ],
        ),
    ]
