# Generated by Django 4.2.1 on 2023-06-16 14:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_alter_basket_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="basket",
            managers=[],
        ),
    ]
