# Generated by Django 4.2.1 on 2023-06-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='media/images/example.jpg', null=True, upload_to='products_images'),
        ),
    ]
